In [1]:
#importing necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
#reading the csv file with pandas
df = pd.read_csv('./Downloads/merged_saudi_github_thabtah_toddler_child.csv')
df.head()

A1  A2  A3  A4  A5  A6  A7  A8  A9  A10  Class    src
0   0   0   0   0   0   1   1   1   0    0      0  Saudi
1   0   0   1   0   1   0   0   1   0    0      0  Saudi
2   0   0   0   0   0   0   1   0   0    0      0  Saudi
3   0   0   0   0   0   0   0   0   0    0      0  Saudi
4   0   0   0   0   0   0   0   0   0    0      0  Saudi

In [3]:
df.shape

(2566, 12)

the dataset has 2566 rows and 12 columns

In [4]:
df.columns

Index(['A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'A9', 'A10', 'Class',
       'src'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2566 entries, 0 to 2565
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   A1      2566 non-null   int64 
 1   A2      2566 non-null   int64 
 2   A3      2566 non-null   int64 
 3   A4      2566 non-null   int64 
 4   A5      2566 non-null   int64 
 5   A6      2566 non-null   int64 
 6   A7      2566 non-null   int64 
 7   A8      2566 non-null   int64 
 8   A9      2566 non-null   int64 
 9   A10     2566 non-null   int64 
 10  Class   2566 non-null   int64 
 11  src     2566 non-null   object
dtypes: int64(11), object(1)
memory usage: 240.7+ KB


In [6]:
df.describe()

A1           A2           A3           A4           A5  \
count  2566.000000  2566.000000  2566.000000  2566.000000  2566.000000   
mean      0.563133     0.461808     0.460249     0.516758     0.552221   
std       0.496095     0.498636     0.498515     0.499817     0.497362   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       1.000000     0.000000     0.000000     1.000000     1.000000   
75%       1.000000     1.000000     1.000000     1.000000     1.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

                A6           A7           A8           A9          A10  \
count  2566.000000  2566.000000  2566.000000  2566.000000  2566.000000   
mean      0.577942     0.623149     0.483632     0.491037     0.607171   
std       0.493984     0.484692     0.499829     0.500017     0.488475   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       1.000000     1.000000     0.000000     0.000000     1.000000   
75%       1.000000     1.000000     1.000000     1.000000     1.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

             Class  
count  2566.000000  
mean      0.657054  
std       0.474786  
min       0.000000  
25%       0.000000  
50%       1.000000  
75%       1.000000  
max       1.000000

In [7]:
df.nunique()

A1       2
A2       2
A3       2
A4       2
A5       2
A6       2
A7       2
A8       2
A9       2
A10      2
Class    2
src      4
dtype: int64

Attributes:

A1-A10: Items within Q-Chat-10  in which questions possible answers : “Always, Usually, Sometimes, Rarly & Never” items’ values are mapped to “1” or “0” in the dataset. For questions 1-9 (A1-A9) in Q-chat-10,  if the respose was  Sometimes / Rarly / Never “1” is assigned to the question (A1-A9). However, for question 10 (A10), if the respose was Always / Usually / Sometimes then “1” is assigned to that question. If the user obtained More than 3 Add points together for all ten questions. If your child scores more than 3 (Q-chat-10- score) then there is a potential ASD traits otherwise no ASD traits are observed.


In [8]:
df['Class'].value_counts()

1    1686
0     880
Name: Class, dtype: int64

DATA CLEANING

In [9]:
df.isna().sum()

A1       0
A2       0
A3       0
A4       0
A5       0
A6       0
A7       0
A8       0
A9       0
A10      0
Class    0
src      0
dtype: int64

THE DATASET HAS NO MISSING VALUE

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2566 entries, 0 to 2565
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   A1      2566 non-null   int64 
 1   A2      2566 non-null   int64 
 2   A3      2566 non-null   int64 
 3   A4      2566 non-null   int64 
 4   A5      2566 non-null   int64 
 5   A6      2566 non-null   int64 
 6   A7      2566 non-null   int64 
 7   A8      2566 non-null   int64 
 8   A9      2566 non-null   int64 
 9   A10     2566 non-null   int64 
 10  Class   2566 non-null   int64 
 11  src     2566 non-null   object
dtypes: int64(11), object(1)
memory usage: 240.7+ KB


In [11]:
df['src'].value_counts()

thabtah_toddler    1054
github              714
Saudi               506
UCI_child           292
Name: src, dtype: int64

In [12]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
df['src'] = encoder.fit_transform(df['src'])

In [13]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.metrics import classification_report



X = df.drop('Class', axis=1)
y = df['Class']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=12345)





MODEL TRAINING

LOGISTIC REGRESSION

In [15]:
# Train the model
log_reg_model = LogisticRegression()
log_reg_model.fit(X_train, y_train)

# Predict on the test set
y_pred = log_reg_model.predict(X_test)

# Evaluate the model
acc = accuracy_score(y_test, y_pred)
print("Accuracy: ", acc)
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion matrix: \n", conf_matrix)

Accuracy:  0.9377431906614786
Confusion matrix: 
 [[150  19]
 [ 13 332]]


In [16]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.92      0.89      0.90       169
           1       0.95      0.96      0.95       345

    accuracy                           0.94       514
   macro avg       0.93      0.92      0.93       514
weighted avg       0.94      0.94      0.94       514



SUPPORT VECTOR MACHINES

In [17]:
from sklearn.svm import SVC
svc_model = SVC()
svc_model.fit(X_train,y_train)

# Predict on the test set
y_pred = svc_model.predict(X_test)

# Evaluate the model
acc = accuracy_score(y_test, y_pred)
print("Accuracy: ", acc)
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion matrix: \n", conf_matrix)

Accuracy:  0.9610894941634242
Confusion matrix: 
 [[156  13]
 [  7 338]]


In [18]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.96      0.92      0.94       169
           1       0.96      0.98      0.97       345

    accuracy                           0.96       514
   macro avg       0.96      0.95      0.96       514
weighted avg       0.96      0.96      0.96       514



K-NEAREST NEIGHBOURS

In [22]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score


# Train the KNN model
knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train, y_train)

# Evaluate the model on the test set
y_pred = knn_model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.9182879377431906


In [23]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.85      0.91      0.88       169
           1       0.95      0.92      0.94       345

    accuracy                           0.92       514
   macro avg       0.90      0.92      0.91       514
weighted avg       0.92      0.92      0.92       514



HYPER PARAMETER TUNING WITH RANDOMIZED SEARCH CV TO GET BETTER RESULTS

LOGISTIC REGRESSION

In [28]:
# Define the parameter grid for Randomized Search
param_grid = {
    'penalty': ['l1', 'l2', 'elasticnet', 'none'],
    'C': np.logspace(-4, 4, 20),
    'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga'],
    'max_iter': [100, 1000, 10000, 100000],
    'fit_intercept': [True, False],
    'warm_start': [True, False]
}

# Initialize the Logistic Regression model
model = LogisticRegression()

# Perform Randomized Search with Cross Validation
rand_search = RandomizedSearchCV(model, param_distributions=param_grid, n_iter=100, cv=10, n_jobs=-1, random_state=12345)
rand_search.fit(X_train, y_train)

# Get the best hyperparameters
best_params = rand_search.best_params_
print(best_params)


{'warm_start': False, 'solver': 'newton-cg', 'penalty': 'l2', 'max_iter': 100, 'fit_intercept': True, 'C': 0.03359818286283781}


In [29]:
# Train the model with the best hyperparameters
model = LogisticRegression(**best_params)
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model using Confusion Matrix and Classification Report
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("Classification Report:")
print(classification_report(y_test, y_pred))



Confusion Matrix:
[[148  21]
 [ 10 335]]
Classification Report:
              precision    recall  f1-score   support

           0       0.94      0.88      0.91       169
           1       0.94      0.97      0.96       345

    accuracy                           0.94       514
   macro avg       0.94      0.92      0.93       514
weighted avg       0.94      0.94      0.94       514



SUPPORT VECTOR MACHINES

In [30]:
# define the parameter grid for hyperparameter tuning
param_grid = {
    "C": np.logspace(-3, 3, 7),
    "gamma": np.logspace(-3, 3, 7),
    "kernel": ["linear", "rbf"]
}

# create a SVC classifier
svc = SVC()

# use RandomizedSearchCV to perform hyperparameter tuning
random_search = RandomizedSearchCV(svc, param_grid, n_iter=100, cv=10, scoring="accuracy", verbose=0, n_jobs=-1)

# fit the RandomizedSearchCV object to the training data
random_search.fit(X_train, y_train)

# predict on the test set
y_pred = random_search.predict(X_test)

# evaluate the model using confusion matrix and classification report
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))




Confusion Matrix:
[[166   3]
 [  4 341]]

Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.98      0.98       169
           1       0.99      0.99      0.99       345

    accuracy                           0.99       514
   macro avg       0.98      0.99      0.98       514
weighted avg       0.99      0.99      0.99       514



K- NEAREST NEIGHBOURS

In [31]:

# define the parameter grid for hyperparameter tuning
param_grid = {
    "n_neighbors": np.arange(1, 31),
    "weights": ["uniform", "distance"],
    "metric": ["euclidean", "manhattan"]
}

# create a KNeighborsClassifier
knn = KNeighborsClassifier()

# use RandomizedSearchCV to perform hyperparameter tuning
random_search = RandomizedSearchCV(knn, param_grid, n_iter=100, cv=10, scoring="accuracy", verbose=0, n_jobs=-1)

# fit the RandomizedSearchCV object to the training data
random_search.fit(X_train, y_train)

# predict on the test set
y_pred = random_search.predict(X_test)

# evaluate the model using confusion matrix and classification report
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))




Confusion Matrix:
[[158  11]
 [ 11 334]]

Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.93      0.93       169
           1       0.97      0.97      0.97       345

    accuracy                           0.96       514
   macro avg       0.95      0.95      0.95       514
weighted avg       0.96      0.96      0.96       514



CONCLUSION:

BEST MODEL SO FAR AFTER TUNING PARAMETERS IS SVM